// AUTO MAINTAINED FILE: DO NOT CHANGE

export const HOME_ADD_READ_ROBOTS_TXT = 'HOME_ADD_READ_ROBOTS_TXT';
export const HOME_FETCH_ROBOTS_TXT_BEGIN = 'HOME_FETCH_ROBOTS_TXT_BEGIN';
export const HOME_FETCH_ROBOTS_TXT_SUCCESS = 'HOME_FETCH_ROBOTS_TXT_SUCCESS';
export const HOME_FETCH_ROBOTS_TXT_FAILURE = 'HOME_FETCH_ROBOTS_TXT_FAILURE';
export const HOME_FETCH_ROBOTS_TXT_DISMISS_ERROR = 'HOME_FETCH_ROBOTS_TXT_DISMISS_ERROR';
export const HOME_CLEAR_ROBOTS_TXT = 'HOME_CLEAR_ROBOTS_TXT';
export const HOME_ADD_ROBOTTXT_TO_DB_BEGIN = 'HOME_ADD_ROBOTTXT_TO_DB_BEGIN';
export const HOME_ADD_ROBOTTXT_TO_DB_SUCCESS = 'HOME_ADD_ROBOTTXT_TO_DB_SUCCESS';
export const HOME_ADD_ROBOTTXT_TO_DB_FAILURE = 'HOME_ADD_ROBOTTXT_TO_DB_FAILURE';
export const HOME_ADD_ROBOTTXT_TO_DB_DISMISS_ERROR = 'HOME_ADD_ROBOTTXT_TO_DB_DISMISS_ERROR';
export const HOME_CHANGE_PAGE_TITLE = 'HOME_CHANGE_PAGE_TITLE';
export const HOME_FETCH_ROBOTS_TXT_LIST_BEGIN = 'HOME_FETCH_ROBOTS_TXT_LIST_BEGIN';
export const HOME_FETCH_ROBOTS_TXT_LIST_SUCCESS = 'HOME_FETCH_ROBOTS_TXT_LIST_SUCCESS';
export const HOME_FETCH_ROBOTS_TXT_LIST_FAILURE = 'HOME_FETCH_ROBOTS_TXT_LIST_FAILURE';
export const HOME_FETCH_ROBOTS_TXT_LIST_DISMISS_ERROR = 'HOME_FETCH_ROBOTS_TXT_LIST_DISMISS_ERROR';
export const HOME_DELETE_ROBOTS_TXT_BEGIN = 'HOME_DELETE_ROBOTS_TXT_BEGIN';
export const HOME_DELETE_ROBOTS_TXT_SUCCESS = 'HOME_DELETE_ROBOTS_TXT_SUCCESS';
export const HOME_DELETE_ROBOTS_TXT_FAILURE = 'HOME_DELETE_ROBOTS_TXT_FAILURE';
export const HOME_DELETE_ROBOTS_TXT_DISMISS_ERROR = 'HOME_DELETE_ROBOTS_TXT_DISMISS_ERROR';
