// AUTO MAINTAINED FILE: DO NOT CHANGE

export const HOME_ADD_READ_ROBOTS_TXT = 'HOME_ADD_READ_ROBOTS_TXT';
export const HOME_FETCH_ROBOTTXT_BEGIN = 'HOME_FETCH_ROBOTTXT_BEGIN';
export const HOME_FETCH_ROBOTTXT_SUCCESS = 'HOME_FETCH_ROBOTTXT_SUCCESS';
export const HOME_FETCH_ROBOTTXT_FAILURE = 'HOME_FETCH_ROBOTTXT_FAILURE';
export const HOME_FETCH_ROBOTTXT_DISMISS_ERROR = 'HOME_FETCH_ROBOTTXT_DISMISS_ERROR';
export const HOME_CLEAR_ROBOTTXT = 'HOME_CLEAR_ROBOTTXT';
export const HOME_ADD_ROBOTTXT_TO_DB_BEGIN = 'HOME_ADD_ROBOTTXT_TO_DB_BEGIN';
export const HOME_ADD_ROBOTTXT_TO_DB_SUCCESS = 'HOME_ADD_ROBOTTXT_TO_DB_SUCCESS';
export const HOME_ADD_ROBOTTXT_TO_DB_FAILURE = 'HOME_ADD_ROBOTTXT_TO_DB_FAILURE';
export const HOME_ADD_ROBOTTXT_TO_DB_DISMISS_ERROR = 'HOME_ADD_ROBOTTXT_TO_DB_DISMISS_ERROR';
export const HOME_CHANGE_PAGE_TITLE = 'HOME_CHANGE_PAGE_TITLE';
